### ISSUE TITLE
can't reproduce the tSNE plot of zheng17.

### ISSUE THREAD

**Issue by ponnhide** [theislab/scanpy_usage#10]
I tried to reproduce the tSNE plot of [170503_zheng17](https://github.com/theislab/scanpy_usage/tree/master/170503_zheng17).

However, I can't reproduce it. I used the following script.

```py
adata = sc.read(path + 'matrix.mtx', cache=True).T
adata.var_names = pd.read_csv(path + 'genes.tsv', header=None, sep='\t')[1]
adata.obs_names = pd.read_csv(path + 'barcodes.tsv', header=None)[0]
adata.var_names_make_unique()
adata.obs['bulk_labels'] = pd.read_csv('./zheng17_bulk_lables.txt', header=None)[0].values
adata = adata[:use_first_n_observations]

sc.pp.filter_genes(adata, min_counts=1)
sc.pp.normalize_per_cell(adata)
filter_result = sc.pp.filter_genes_dispersion(
	adata.X, flavor='cell_ranger', n_top_genes=1000, log=False)
sc.logging.print_memory_usage()
sc.pl.filter_genes_dispersion(filter_result, log=True, show=False, save="hoge.pdf")
adata = adata[:, filter_result.gene_subset]
sc.pp.normalize_per_cell(adata)
sc.pp.log1p(adata)
sc.pp.scale(adata)
sc.tl.pca(adata, n_comps=50, svd_solver='arpack')
sc.logging.print_memory_usage()
sc.pl.pca_loadings(adata,save="hoge.pdf")

sc.tl.tsne(adata)
sc.pl.tsne(adata, color='bulk_labels', show=False, save="hoge.pdf")
```

The pakages environments I used are scanpy==1.0.4 anndata==0.6.16 numpy==1.14.1 scipy==1.0.0 pandas==0.21.0 scikit-learn==0.19.1 statsmodels==0.8.0.

The following figure is a tSNE plot I produced. However, the plot is a little different from the original one.

![image](https://user-images.githubusercontent.com/2762763/50871829-4283cc00-1400-11e9-9447-dfb2ee21f1ff.png)

How do I change the script to reproduce the original t-SNE plot?

**Comment by flying-sheep** [comment]
For comparison:

![grafik](https://user-images.githubusercontent.com/291575/50890906-685aa200-13fb-11e9-8b7e-1fd37f445842.png)

Isn’t that expected due to the stochastic nature of t-SNE?

Qualitatively they seem the same: the CD19+ B cells have a little nook, part of the CD56+ NK cells stand alone, another part transitions into the CD8+ Cytotoxic T cells, …

**Comment by ponnhide** [comment]
Thank you for your kind response.
I understood your explanation.

However, in the tSNE method of scanpy, the default random seed is set as 0, not random, right?
Therefore, I thought that the exact same result with original one should be reproduced.

Are there no problems in practical?

**Comment by flying-sheep** [comment]
Well, whenever something using the random machinery is added before another call that does it, things change anyway. So sadly you can never rely on t-SNEs to stay the same as soon as you update any dependency.

@falexwolf might know more details though!

**Comment by falexwolf** [comment]
It is indeed sometimes hard to get *exactly* the same tSNE plot if not all dependencies match. In case you have some numerical inaccuracy due to some reason that can amplify and give you tSNEs or UMAPs with a different appearance. Usually, the most critical step is the PCA.

However, your tSNE and the tSNE from the reference notebook agree in their connectivity structure, and hence, in their biological interpretation. The same types of cells form clusters in both tSNEs.

How about the basic tutorial: https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html should look exactly as it does online, right? I haven't run the `zheng17` notebook for a long time and I even removed it from the webpage. As soon as I have some bandwidth, I'll look into it again... change the output to a UMAP, and maybe play around with the number of PCs or the floating point precision to get something that looks exactly on every machine with some robustness regarding changed dependencies.
